language: node_js
node_js:
  - 18.17.1

cache:
  directories:
    - node_modules

branches:
  only:
    - main

before_install:
  - npm install -g npm@latest

install:
  - npm install

script:
  - npm test

#deploy:#  provider: heroku#  api_key:#    secure: heroku_api_key#    app: _heroku_app_namenotifications:
  email:
    recipients:
      - katya162157@gmail.com
    on_success: always
    on_failure: always